version: '3'
services:
  pw:
    environment: 
       - VIRTUAL_HOST=yourapp.localtest.me # *.localtest.me subdomains will always point to 127.0.0.1 on every computer in the world...easy way to use multiple hostnames on a windows dev machine.
     depends_on:
       - db
     image: gebeer/alpine-php-processwire
     networks:
       - default
       - proxy
     volumes:
       - ./src:/DATA/htdocs
       - ./logs:/DATA/logs
   
   db:
     image: mariadb
     networks:
       - default
     volumes:
       - mysql:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=rootpassword
       - MYSQL_DATABASE=processwire
       - MYSQL_USER=processwire
       - MYSQL_PASSWORD=password

volumes:
  mysql:

networks:
  proxy:
    external: true