version: '3'
services:
  pw:
    environment: 
      - VIRTUAL_HOST=myapp.localtest.me # *.localtest.me subdomains will always point to 127.0.0.1 on every computer in the world...easy way to use multiple hostnames on a windows dev machine.
    build:
      args:
        - docker_hostip=10.7.0.164 #REPLACE this IP with the LAN IP of your host machine. (This is so Xdebug can communicate with your IDE on host machine).
      context: .
      dockerfile: app-dockerfile
    image: joel-alpine-php-processwire
    depends_on:
      - db
    networks:
      - default
      - proxy
    volumes:
      - ./src:/DATA/htdocs
      - ./logs:/DATA/logs
  
  db:
    image: mariadb
    networks:
      - default
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=processwire
      - MYSQL_USER=processwire
      - MYSQL_PASSWORD=password

volumes:
  mysql:

networks:
  proxy:
    external: true