version: '3'
services:
  pw:
    environment: 
       - VIRTUAL_HOST=missions.localtest.me
     depends_on:
       - db
     image: gebeer/alpine-php-processwire
     networks:
       - default
       - proxy
     volumes:
       - ./src:/DATA/htdocs
       - ./logs:/DATA/logs
   
   db:
     image: mariadb
     networks:
       - default
     volumes:
       - mysql:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=rootpassword
       - MYSQL_DATABASE=processwire
       - MYSQL_USER=processwire
       - MYSQL_PASSWORD=password

volumes:
  mysql:

networks:
  proxy:
    external: true